services:
  glms-sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: glms-sql-compose
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password@2026"
    ports:
      - "1434:1433"

  glms-api:
    build:
      context: .
      dockerfile: GLMS.Api/Dockerfile
    container_name: glms-api
    ports:
      - "5155:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=glms-sql;Database=GLMSDb;User Id=sa;Password=Password@2026;TrustServerCertificate=True;"
    depends_on:
      - glms-sql

  glms-web:
    build:
      context: .
      dockerfile: GLMS.Web/Dockerfile
    container_name: glms-web
    ports:
      - "5007:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      GLMSApi__BaseUrl: "http://glms-api:8080/"
    depends_on:
      - glms-api